title: Frank De Graeve
description: Frank De Graeve is a Design Director specialising in DesignOps, UX Strategy, and AI Adoption. Based in Belgium.
social_media_share_image: /images/01.jpg
disqus-identifier:
google-analytics: